# Generated by Django 2.0 on 2020-06-14 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='averageRating',
            new_name='average_rating',
        ),
    ]
