# Generated by Django 2.0 on 2020-06-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_reviewg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
